# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = match:class ^(microsoft-edge)$, tile on
windowrule = match:class ^(chromium)$, tile on
windowrule = match:class ^(pavucontrol)$, float true
windowrule = match:class ^(blueman-manager)$, float true
windowrule = match:class ^(nm-connection-editor)$, float true
windowrule = match:class ^(qalculate-gtk)$, float true
