# ----------------------------------------------------- 
# ML4W configurations
# ----------------------------------------------------- 

windowrule = float on, match:class (com.ml4w.welcome)
windowrule = size 700 600, match:class (com.ml4w.welcome)
windowrule = center on, match:class (com.ml4w.welcome)

windowrule = float on, match:class (ml4w-welcome.py)
windowrule = size 400 500, match:class (ml4w-welcome.py)
windowrule = center on, match:class (ml4w-welcome.py)

windowrule = float on, match:class (com.ml4w.dotfilessettings)
windowrule = size 700 600, match:class (com.ml4w.dotfilessettings)
windowrule = move 10% 20%, match:class (com.ml4w.dotfilessettings)

windowrule = float on, match:class (ml4w-dotfiles-settings.py)
windowrule = size 400 500, match:class (ml4w-dotfiles-settings.py)
windowrule = move 10% 20%, match:class (ml4w-dotfiles-settings.py)

windowrule = float on, match:class (dotfiles-floating)
windowrule = size 1000 800, match:class (dotfiles-floating)
windowrule = center on, match:class (dotfiles-floating)

env = APPIMAGELAUNCHER_DISABLE,1
