working_directory = "/home/martinit/my/tmp"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x202020"
foreground = "0xffffff"

[env]
TERM = "alacritty"

[font]
size = 18.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = '([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|([0-9a-f]{12,128})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

[hints.enabled.binding]
key = "H"
mods = "Control|Shift"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
